
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 29 17:34:07 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int LT = 7;
  public static final int OVER = 12;
  public static final int ELSE = 3;
  public static final int PLUS = 9;
  public static final int INT = 24;
  public static final int RPAREN = 14;
  public static final int WHILE = 26;
  public static final int SEMI = 15;
  public static final int RCURLY = 19;
  public static final int RETURN = 4;
  public static final int ERROR = 29;
  public static final int IF = 2;
  public static final int LPAREN = 13;
  public static final int GT = 8;
  public static final int ID = 27;
  public static final int NUM = 28;
  public static final int LCURLY = 18;
  public static final int COMMA = 20;
  public static final int LTEQ = 22;
  public static final int EOF = 0;
  public static final int MINUS = 10;
  public static final int LSQUARE = 16;
  public static final int error = 1;
  public static final int ASSIGN = 5;
  public static final int EQ = 6;
  public static final int RSQUARE = 17;
  public static final int GTEQ = 23;
  public static final int VOID = 25;
  public static final int NEQ = 21;
}

